[package]
name = "typed-sql-type-gen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.64"
sqlite3-parser = "0.9.0"
wasm-bindgen = "0.2.87"

[profile.release]
lto = true
